### ISSUE TITLE
Incorrect certificate for notification.choo.io

### ISSUE THREAD

**Issue by jbergstroem** [choojs/choo-notification#1]
..seems to present a netlify one:
<center>
<img width="436" alt="screen shot 2018-02-22 at 10 04 32 am" src="https://user-images.githubusercontent.com/176984/36540094-d1a6e110-17b7-11e8-8141-5f5e98e3d2fd.png"></center>

**Comment by bcomnes** [comment]
Thanks for the heads up.  Sometimes there can be issue when auto-renewing letsencrypt certs.

**Comment by bcomnes** [comment]
Looks like https wasn't enabled for this site yet.  @yoshuawuyts want to add it to the choo netlify team so I an help mange ?

**Comment by bcomnes** [comment]
Ok should be working
